<a href="https://colab.research.google.com/github/Muhamad-naufal/Project-MSIB-3/blob/main/Exercise_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
NIK = [1990022, 2001077, 2002019, 2002081, 2005099, 2006003, 2006104, 2008160] 
Nama = ['Herman', 'Badar', 'Clara', 'Rista', 'Riani', 'Afif', 'Riven', 'Endah']
Jenis_Kelamin = ['L', 'L', 'P', 'P', 'P', 'L', 'L', 'P']
Alamat = ['Tangerang', 'Bekasi', 'Depok', 'Bogor', 'Bekasi', 'Karawang', 'Tangerang', 'Jakarta']
Divisi = ['Machinery', 'Machinery', 'Compressor', 'QC', 'QC', 'Compressor', 'Compressor', 'Machinery']
Jabatan = ['Manager', 'Staff', 'Staff', 'Staff', 'Operator', 'Operator', 'Operator']
Gaji_Pokok = [10000000, 7500000, 7000000, 6500000, 6000000, 5500000, 5500000, 5000000]

for data in zip(NIK,Nama, Jenis_Kelamin, Alamat, Divisi, Jabatan, Gaji_Pokok):
  print(data)

(1990022, 'Herman', 'L', 'Tangerang', 'Machinery', 'Manager', 10000000)
(2001077, 'Badar', 'L', 'Bekasi', 'Machinery', 'Staff', 7500000)
(2002019, 'Clara', 'P', 'Depok', 'Compressor', 'Staff', 7000000)
(2002081, 'Rista', 'P', 'Bogor', 'QC', 'Staff', 6500000)
(2005099, 'Riani', 'P', 'Bekasi', 'QC', 'Operator', 6000000)
(2006003, 'Afif', 'L', 'Karawang', 'Compressor', 'Operator', 5500000)
(2006104, 'Riven', 'L', 'Tangerang', 'Compressor', 'Operator', 5500000)


In [ ]:
import numpy as np

A = np.array([[1, 2],
              [4, 5],
              [7, 8]])

print(A, '\n')

print(A[2:3, 0:1], 
      A[2:3, 1:2])

[[1 2]
 [4 5]
 [7 8]] 

[[7]] [[8]]


In [ ]:
B = np.array([[1, 6, 9],
              [2, 5, 8]])

print(B, '\n')

print(B[0:1, 1:2], B[1:2, 1:2])

[[1 6 9]
 [2 5 8]] 

[[6]] [[5]]


In [ ]:
C = np.array([[4, 3, 8],
              [7, 2, 5],
              [6, 1, 9]])

print(C, '\n')

print(C[1:2, 1:2])
print(C[2:3, 1:2])

[[4 3 8]
 [7 2 5]
 [6 1 9]] 

[[2]]
[[1]]


In [ ]:
D = np.array([[4, 3, 8],
              [7, 2, 5],
              [6, 1, 9]])

print(D, '\n')

print(D[0:1, 1:2], D[0:1, 2:3])

[[4 3 8]
 [7 2 5]
 [6 1 9]] 

[[3]] [[8]]


In [ ]:
E = np.array([[23, 35, 93, 87],
              [92, 44, 11, 83],
              [40, 12, 46, 28],
              [73, 67, 65, 32]])

print(E, '\n')


print('1 =',E[1:2, 1:2], E[1:2, 2:3], E[1:2, 3:4], '\n')
print('2 =',E[2:3, 1:2], E[2:3, 2:3],'\n', 
            E[3:4, 1:2], E[3:4, 2:3],'\n')
print('3 =',E[1:2, 1:2], E[1:2, 2:3], E[1:2, 3:4],'\n',
            E[2:3, 1:2], E[2:3, 2:3], E[2:3, 3:4],'\n',
            E[3:4, 1:2], E[3:4, 2:3], E[3:4, 3:4],'\n')
print('4 =',E[1:2, 0:1], E[1:2, 1:2],'\n',
            E[2:3, 0:1], E[2:3, 1:2],'\n')
print('5 =',E[0:1, 0:1], E[0:1, 1:2], E[0:1, 2:3], '\n',
            E[1:2, 0:1], E[1:2, 1:2], E[1:2, 2:3], '\n')
print('6 =',E[1:2, 1:2], '\n',
            E[2:3, 1:2], '\n',
            E[3:4, 1:2])

[[23 35 93 87]
 [92 44 11 83]
 [40 12 46 28]
 [73 67 65 32]] 

1 = [[44]] [[11]] [[83]] 

2 = [[12]] [[46]] 
 [[67]] [[65]] 

3 = [[44]] [[11]] [[83]] 
 [[12]] [[46]] [[28]] 
 [[67]] [[65]] [[32]] 

4 = [[92]] [[44]] 
 [[40]] [[12]] 

5 = [[23]] [[35]] [[93]] 
 [[92]] [[44]] [[11]] 

6 = [[44]] 
 [[12]] 
 [[67]]
